[build]
  command = "npm run build"  # Use the TypeScript build script defined in your package.json
  functions = "dist/functions"  # Path to your built serverless functions
  publish = "dist"  # Path to your static assets (if any)

[build.environment]
  NODE_VERSION = "16"  # Specify the Node.js version (adjust as needed)

[build.processing]
  # Specify the TypeScript build command
  - type = "npm"
    command = "run build"  # Use the TypeScript build script defined in your package.json
